config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'posts#index'
  resources :posts, only: %i[index show]
  resources :categories, only: :show
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :access, :rails_admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories/categories_presenter.rb
module Categories
  class CategoriesPresenter
    attr_reader :category_id, :category, :posts_details
    attr_reader :ar_category, :post_detail

    def initialize(category_id, ar_category: Category, post_detail: Posts::Detail)
      @category_id = category_id

      @ar_category = ar_category
      @post_detail = post_detail
    end

    def gather_data
      @category = ar_category.find_by(id: category_id)
      @posts_details = @category&.posts&.map do |post|
        post_detail.new(post)
      end

      self
    end

    def on_present
      yield if @category
    end

    def on_empty
      yield unless @category
    end

    def on_posts_present
      yield if @posts_details
    end

    def on_posts_empty
      yield unless @posts_details
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_posts, dependent: :destroy
  has_many :posts, through: :category_posts
end

app/models/category_post.rb
class CategoryPost < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :preview_image
  has_rich_text :content

  has_many :category_posts
  has_many :categories, through: :category_posts
end

app/models/posts/detail.rb
module Posts
  class Detail
    attr_reader :post

    def initialize(post)
      @post = post
    end

    def preview_image
      post.preview_image
    end

    def created_at
      post.created_at.to_formatted_s(:long_ordinal)
    end

    def id
      post.id
    end

    def description
      post.description
    end

    def title
      post.title
    end

    def content
      post.content
    end
  end
end

app/models/posts/post_presenter.rb
module Posts
  class PostPresenter
    attr_reader :post_id, :post
    attr_reader :ar_post, :detail

    def initialize(
        post_id,
        ar_post: Post,
        detail: Posts::Detail
    )
      @post_id = post_id

      @ar_post = ar_post
      @detail = detail
    end

    def on_present
      yield if post
    end

    def on_empty
      yield unless post
    end

    def post
      @post ||= detail.new(find_post)
    end

    private

    def find_post
      @find_post ||= ar_post.find_by(id: post_id)
    end
  end
end

app/models/posts/posts_presenter.rb
require 'will_paginate/array'

module Posts
  class PostsPresenter
    attr_reader :posts, :page
    attr_reader :ar_post, :post_detail

    def initialize(page, ar_post: Post, post_detail: Posts::Detail)
      @page = page

      @ar_post = ar_post
      @post_detail = post_detail
    end

    def gather_data
      @posts = ar_post.all.map do |post|
        post_detail.new(post)
      end.paginate(page: page, per_page: 3)

      self
    end

    def on_present
      yield if @posts
    end

    def on_empty
      yield unless @posts
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  after_create :assign_default_role

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :header

  def header
    part_category_count = Category.count / 2
    @part_categories = Category.all.each_slice(part_category_count).to_a
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories_presenter = Categories::CategoriesPresenter.new(params[:id]).gather_data
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts_presenter = Posts::PostsPresenter.new(params[:page]).gather_data
  end

  def show
    @post_presenter = Posts::PostPresenter.new(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/categories/show.html.erb
<% @categories_presenter.on_present do %>
  <h1 class="category_name"><%= @categories_presenter.category.name %></h1>

  <div class="container category_c">
    <% @categories_presenter.on_posts_present do %>
      <div class="row">
        <% @categories_presenter.posts_details.each do |post| %>
          <div class="col-md-4 category_1">
            <div class="category">
              <%= image_tag post.preview_image, class: 'image' %>
              <div class="hover_background">
                <div class="hover_link">
                  <%= link_to post.title, post_path(post.id) %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <% @categories_presenter.on_posts_empty do %>
      <p class="category_blank">В данной категории нет записей</p>
    <% end %>
  </div>
<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <span>Здравствуйте, <%= current_user.email %></span>
  <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% end %>

<h1 style="text-align: center;">Init root page. Hi</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
  <div class="container">
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </div>
  </body>
</html>

app/views/posts/index.html.erb
<% @posts_presenter.on_present do %>
  <% @posts_presenter.posts.each do |post| %>
    <div class="blog_post">
      <%= image_tag post.preview_image, class: 'image' %>
      <div class="title">
        <%= link_to post.title, post_path(post.id) %>
      </div>
      <div class="time">
        <%= post.created_at %>
      </div>
      <div class="body">
        <%= post.description %>
      </div>
      <%= link_to 'Read full post', post_path(post.id), class: 'button' %>
    </div>
  <% end %>

  <%= will_paginate @posts_presenter.posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
<% end %>

<% @posts_presenter.on_empty do %>
  <p>В блоге пока нет постов =С</p>
<% end %>

app/views/posts/show.html.erb
<% @post_presenter.on_present do %>
  <div class="blog_post">
    <h2 class="title">
      <%= @post_presenter.post.title %>
    </h2>
    <%= image_tag @post_presenter.post.preview_image, class: 'image' %>
    <div class="body"><%= @post_presenter.post.content %></div>
  </div>
<% end %>

<% @post_presenter.on_empty do %>
  <p>Пост не найден</p>
  <% link_to 'Main page', root_path %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <%= render 'shared/social' %>

  <p>by MaDDi footer 2021 All Rights Reserved</p>
</footer>

app/views/shared/_header.html.erb
<header id="top">
  <%= render 'shared/social' %>

  <div class="row">
    <div class="col-md-4 category">
      <% @part_categories.first.each do |category|  %>
        <div class="col-md-6 category_s"><%= link_to category.name, category_path(category) %></div>
      <% end %>
    </div>

    <div class="col-md-4 category">
      <%= link_to image_tag("logo.png", alt:"Ely Blog"), root_path %>
    </div>

    <div class="col-md-4 category">
      <% @part_categories.last.each do |category|  %>
        <div class="col-md-6 category_s"><%= link_to category.name, category_path(category) %></div>
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_social.html.erb
<div class="social-main">
  <ul>
    <li><a class="shared-tw" href="#" target="_blank"></a></li>
    <li><a class="shared-vk" href="#" target="_blank"></a></li>
    <li><a class="shared-inst" href="#" target="_blank"></a></li>
  </ul>
</div>